version: '3.3'
services:
  mongodb_container:
    image: mongo:latest
    container_name: mongoDB-ethereumTowers
    environment:
      MONGO_INITDB_ROOT_USERNAME: kononov
      MONGO_INITDB_ROOT_PASSWORD: 291091
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - ethereumTowers
volumes:
  mongodb_data_container:

networks:
  ethereumTowers:
    driver: bridge